db_keys = {
    'play_id': 'TEXT PRIMARY KEY',
    'game_pk': 'INTEGER',
    'league': 'TEXT',
    'date': 'TEXT',
    'inning': 'INTEGER',
    'at_bat_index': 'INTEGER',
    'event': 'TEXT',
    'event_type': 'TEXT',
    'description': 'TEXT',
    'rbi': 'INTEGER',
    'batter_name': 'TEXT',
    'batter_id': 'INTEGER',
    'bat_side': 'TEXT',
    'pitcher_name': 'TEXT',
    'pitcher_id': 'INTEGER',
    'pitch_hand': 'TEXT',
    'pitch_result': 'TEXT',
    'launch_speed': 'REAL',
    'launch_angle': 'REAL',
    'total_distance': 'REAL',
    'trajectory': 'TEXT',
    'hardness': 'TEXT',
    'location': 'TEXT',
    'coord_x': 'REAL',
    'coord_y': 'REAL',
    'pitch_result_code': 'TEXT',
    'ball_color': 'TEXT',
    'trail_color': 'TEXT',
    'is_in_play': 'INTEGER',
    'is_strike': 'INTEGER',
    'is_ball': 'INTEGER',
    'pitch_code': 'TEXT',
    'pitch_name': 'TEXT',
    'is_out': 'INTEGER',
    'balls': 'INTEGER',
    'strikes': 'INTEGER',
    'outs': 'INTEGER',
    'start_speed': 'REAL',
    'end_speed': 'REAL',
    'strike_zone_top': 'REAL',
    'strike_zone_bottom': 'REAL',
    'strike_zone_width': 'REAL',
    'strike_zone_depth': 'REAL',
    'a_y': 'REAL',
    'a_z': 'REAL',
    'pfx_x': 'REAL',
    'pfx_z': 'REAL',
    'p_x': 'REAL',
    'p_z': 'REAL',
    'v_x0': 'REAL',
    'v_y0': 'REAL',
    'v_z0': 'REAL',
    'x': 'REAL',
    'y': 'REAL',
    'x0': 'REAL',
    'y0': 'REAL',
    'z0': 'REAL',
    'a_x': 'REAL',
    'break_angle': 'REAL',
    'break_length': 'REAL',
    'break_y': 'REAL',
    'break_vertical': 'REAL',
    'break_vertical_induced': 'REAL',
    'break_horizontal': 'REAL',
    'spin_rate': 'INTEGER',
    'spin_direction': 'INTEGER',
    'zone': 'INTEGER',
    'type_confidence': 'REAL',
    'plate_time': 'REAL',
    'extension': 'REAL',
    'play_events_index': 'INTEGER',
    'pitch_number': 'INTEGER',
    'disengagement_num': 'INTEGER',
    'from_catcher': 'INTEGER',
    'runner_going': 'INTEGER',
    'action_play_id': 'TEXT',
    'start_time': 'TEXT',
    'end_time': 'TEXT',
    'is_pitch': 'INTEGER',
    'type': 'TEXT',
    'away_score': 'INTEGER',
    'home_score': 'INTEGER',
    'half_inning': 'TEXT',
    'is_top_inning': 'INTEGER',
    'is_complete': 'INTEGER',
    'is_scoring_play': 'INTEGER',
    'has_out': 'INTEGER',
    'captivating_index': 'INTEGER',
    'final_balls': 'INTEGER',
    'final_strikes': 'INTEGER',
    'final_outs': 'INTEGER',
    'runner_on_1st': 'INTEGER',
    'runner_on_2nd': 'INTEGER',
    'runner_on_3rd': 'INTEGER',
    'game_type': 'TEXT',
    'game_type_name': 'TEXT',
    'season': 'TEXT',
    'day_night': 'TEXT',
    'time': 'TEXT',
    'venue_name': 'TEXT',
    'venue_id': 'INTEGER',
    'city': 'TEXT',
    'time_zone': 'TEXT',
    'turf_type': 'TEXT',
    'weather_condition': 'TEXT',
    'temp': 'TEXT',
    'wind': 'TEXT',
    'team_batting': 'TEXT',
    'team_batting_id': 'INTEGER',
    'team_batting_abbr': 'TEXT',
    'team_fielding': 'TEXT',
    'team_fielding_id': 'INTEGER',
    'team_fielding_abbr': 'TEXT',
    'official_scorer': 'TEXT'

}

sport_ids = {
    'MLB': 1,
    'AAA': 11,
    'AA': 12,
    'A+': 13,
    'A': 14,
    'ROOKIE BALL': 16,
    'WINTER LEAGUE': 17,
    'IND': 23
}

reversed_sport_ids = {
    1: 'MLB',
    11: 'AAA',
    12: 'AA',
    13: 'A+',
    14: 'A',
    16: 'ROOKIE BALL',
    17: 'WINTER LEAGUE',
    23: 'IND'
}

all_leagues = ['MLB', 'AAA', 'AA', 'A+', 'A', 'ROOKIE BALL', 'WINTER LEAGUE']

at_bat_events = [
    'Double', 'Strikeout', 'Flyout', 'Single', 'Forceout', 'Pop Out', 'Groundout',
    'GIDP', 'Field Error', 'Lineout', 'Fielders Choice', 'Double Play', 'Home Run', 'Stolen Base 3B', 'Triple',
    'Fielders Choice Out', 'Batter Out', 'Field Out', 'Strikeout Double Play', 'Bunt Pop Out',
    'Bunt Lineout', 'Bunt Groundout', 'Field Out', 'Batter Out', 'Triple Play', 'Runner Double Play'
]

pitch_names = [
    'Sinker', 'Slider', 'Changeup', 'Curveball', 'Cutter', '4-Seam Fastball',
    'Splitter', 'Sweeper', 'Knuckle Curve', 'Knuckle Ball', 'Slurve', 'Slow Curve',
    'Fastball', 'Eephus', 'Forkball', 'Screwball', '2-Seam Fastball'
]

game_types = {
    'S': 'Spring Training',
    'R': 'Regular Season',
    'F': 'Wild Card Game',
    'D': 'Division Series',
    'L': 'League Championship Series',
    'W': 'World Series',
    'C': 'Championship',
    'N': 'Nineteenth Century Series',
    'P': 'Playoffs',
    'A': 'All-Star Game',
    'I': 'Intrasquad',
    'E': 'Exhibition'
}

pitcher_db_keys = {
    'game_pk': 'INTEGER',
    'date': 'TEXT',
    'name': 'TEXT',
    'league': 'TEXT',
    'player_id': 'INTEGER',
    'jersey_number': 'TEXT',
    'position': 'TEXT',
    'position_code': 'TEXT',
    'note': 'TEXT',
    'summary': 'TEXT',
    'games_played': 'INTEGER',
    'games_started': 'INTEGER',
    'fly_outs': 'INTEGER',
    'ground_outs': 'INTEGER',
    'air_outs': 'INTEGER',
    'runs': 'INTEGER',
    'doubles': 'INTEGER',
    'triples': 'INTEGER',
    'home_runs': 'INTEGER',
    'strike_outs': 'INTEGER',
    'base_on_balls': 'INTEGER',
    'intentional_walks': 'INTEGER',
    'hits': 'INTEGER',
    'hit_by_pitch': 'INTEGER',
    'at_bats': 'INTEGER',
    'caught_stealing': 'INTEGER',
    'stolen_bases': 'INTEGER',
    'stolen_base_percentage': 'TEXT',
    'number_of_pitches': 'INTEGER',
    'innings_pitched': 'TEXT',
    'wins': 'INTEGER',
    'losses': 'INTEGER',
    'saves': 'INTEGER',
    'save_opportunities': 'INTEGER',
    'holds': 'INTEGER',
    'blown_saves': 'INTEGER',
    'earned_runs': 'INTEGER',
    'batters_faced': 'INTEGER',
    'outs': 'INTEGER',
    'games_pitched': 'INTEGER',
    'complete_games': 'INTEGER',
    'shutouts': 'INTEGER',
    'pitches_thrown': 'INTEGER',
    'balls': 'INTEGER',
    'strikes': 'INTEGER',
    'strike_percentage': 'TEXT',
    'hit_batsmen': 'INTEGER',
    'balks': 'INTEGER',
    'wild_pitches': 'INTEGER',
    'pickoffs': 'INTEGER',
    'rbi': 'INTEGER',
    'games_finished': 'INTEGER',
    'runs_scored_per9': 'TEXT',
    'home_runs_per9': 'TEXT',
    'inherited_runners': 'INTEGER',
    'inherited_runners_scored': 'INTEGER',
    'catchers_interference': 'INTEGER',
    'sac_bunts': 'INTEGER',
    'sac_flies': 'INTEGER',
    'passed_ball': 'INTEGER',
    'pop_outs': 'INTEGER',
    'line_outs': 'INTEGER',
    'game_type': 'TEXT',
    'game_type_name': 'TEXT',
    'season': 'TEXT',
    'day_night': 'TEXT',
    'time': 'TEXT',
    'venue_name': 'TEXT',
    'venue_id': 'INTEGER',
    'city': 'TEXT',
    'time_zone': 'TEXT',
    'turf_type': 'TEXT',
    'weather_condition': 'TEXT',
    'temp': 'TEXT',
    'wind': 'TEXT',
    'team_name': 'TEXT',
    'team_id': 'INTEGER',
    'team_abbr': 'TEXT'
}

hitter_db_keys = {
    'game_pk': 'INTEGER',
    'date': 'TEXT',
    'name': 'TEXT',
    'league': 'TEXT',
    'player_id': 'INTEGER',
    'jersey_number': 'TEXT',
    'position': 'TEXT',
    'position_code': 'TEXT',
    'summary': 'TEXT',
    'games_played': 'INTEGER',
    'fly_outs': 'INTEGER',
    'ground_outs': 'INTEGER',
    'air_outs': 'INTEGER',
    'runs': 'INTEGER',
    'doubles': 'INTEGER',
    'triples': 'INTEGER',
    'home_runs': 'INTEGER',
    'strike_outs': 'INTEGER',
    'base_on_balls': 'INTEGER',
    'intentional_walks': 'INTEGER',
    'hits': 'INTEGER',
    'hit_by_pitch': 'INTEGER',
    'at_bats': 'INTEGER',
    'caught_stealing': 'INTEGER',
    'stolen_bases': 'INTEGER',
    'stolen_base_percentage': 'TEXT',
    'ground_into_double_play': 'INTEGER',
    'ground_into_triple_play': 'INTEGER',
    'plate_appearances': 'INTEGER',
    'total_bases': 'INTEGER',
    'rbi': 'INTEGER',
    'left_on_base': 'INTEGER',
    'sac_bunts': 'INTEGER',
    'sac_flies': 'INTEGER',
    'catchers_interference': 'INTEGER',
    'pickoffs': 'INTEGER',
    'at_bats_per_home_run': 'TEXT',
    'pop_outs': 'INTEGER',
    'line_outs': 'INTEGER',
    'game_type': 'TEXT',
    'game_type_name': 'TEXT',
    'season': 'TEXT',
    'day_night': 'TEXT',
    'time': 'TEXT',
    'venue_name': 'TEXT',
    'venue_id': 'INTEGER',
    'city': 'TEXT',
    'time_zone': 'TEXT',
    'turf_type': 'TEXT',
    'weather_condition': 'TEXT',
    'temp': 'TEXT',
    'wind': 'TEXT',
    'team_name': 'TEXT',
    'team_id': 'INTEGER',
    'team_abbr': 'TEXT'
}

fielder_db_keys = {
    'game_pk': 'INTEGER',
    'date': 'TEXT',
    'name': 'TEXT',
    'league': 'TEXT',
    'player_id': 'INTEGER',
    'jersey_number': 'TEXT',
    'position': 'TEXT',
    'position_code': 'TEXT',
    'caught_stealing': 'INTEGER',
    'stolen_bases': 'INTEGER',
    'stolen_base_percentage': 'TEXT',
    'assists': 'INTEGER',
    'put_outs': 'INTEGER',
    'errors': 'INTEGER',
    'chances': 'INTEGER',
    'fielding': 'TEXT',
    'passed_ball': 'INTEGER',
    'pickoffs': 'INTEGER',
    'game_type': 'TEXT',
    'game_type_name': 'TEXT',
    'season': 'TEXT',
    'day_night': 'TEXT',
    'time': 'TEXT',
    'venue_name': 'TEXT',
    'venue_id': 'INTEGER',
    'city': 'TEXT',
    'time_zone': 'TEXT',
    'turf_type': 'TEXT',
    'weather_condition': 'TEXT',
    'temp': 'TEXT',
    'wind': 'TEXT',
    'team_name': 'TEXT',
    'team_id': 'INTEGER',
    'team_abbr': 'TEXT'
}
requires_pitch_results = ['strike_percent', 'csw_percent', 'swstr_percent', 'ball_percent', 'pitch_results']

play_metrics = {
    'pitcher_name': 'pitcher_name AS name, pitcher_id AS player_id',
    'batter_name': 'batter_name AS name, batter_id AS player_id',
    'league': 'league',
    'pitch_name': 'pitch_name',
    'count': 'COUNT(*) AS count',
    'pitch_results': 'GROUP_CONCAT(pitch_result) AS pitch_results',
    'hit_speeds': 'GROUP_CONCAT(launch_speed) AS hit_speeds',
    'percentile_90': 'GROUP_CONCAT(launch_speed) AS hit_speeds',
    'launch_angles': 'GROUP_CONCAT(launch_angle) AS launch_angles',
    'avg_ev': 'AVG(CAST(launch_speed AS REAL)) AS avg_ev',
    'max_ev': 'MAX(CAST(launch_speed AS REAL)) AS max_ev',
    'avg_hit_angle': 'AVG(CAST(launch_angle AS REAL)) AS avg_hit_angle',
    'bip': 'SUM(CASE WHEN pitch_result LIKE "%play%" THEN 1 ELSE 0 END) AS bip',
    'zones': 'GROUP_CONCAT(IFNULL(zone, 0)) as zones',
    'barrel_per_bbe': ['GROUP_CONCAT(launch_speed) AS hit_speeds', 'GROUP_CONCAT(launch_angle) AS launch_angles'],
    'contact_percent': ['GROUP_CONCAT(pitch_result) AS pitch_results', 'GROUP_CONCAT(IFNULL(zone, 0)) as zones'],
    'zone_contact': ['GROUP_CONCAT(pitch_result) AS pitch_results', 'GROUP_CONCAT(IFNULL(zone, 0)) as zones'],
    'chase_percent': ['GROUP_CONCAT(pitch_result) AS pitch_results', 'GROUP_CONCAT(IFNULL(zone, 0)) as zones'],
    'swing_percent': ['GROUP_CONCAT(pitch_result) AS pitch_results', 'GROUP_CONCAT(IFNULL(zone, 0)) as zones'],
    'zone_swing_percent': ['GROUP_CONCAT(pitch_result) AS pitch_results', 'GROUP_CONCAT(IFNULL(zone, 0)) as zones'],
    'avg_velo': 'AVG(CAST(start_speed AS REAL)) AS avg_velo',
    'max_velo': 'MAX(CAST(start_speed AS REAL)) AS max_velo',
    'avg_spin': 'AVG(CAST(spin_rate AS REAL)) AS avg_spin',
    'v_break': 'AVG(CAST(pfx_z AS REAL)) AS v_break',
    'h_break': 'AVG(CAST(pfx_x AS REAL)) AS h_break',
}

total_metrics = {
    'name': 'name',
    'player_id': 'player_id',
    'league': 'league',
    'IP': 'SUM(innings_pitched) AS IP',
    'ERA': '9 * SUM(earned_runs) / SUM(innings_pitched) AS ERA',
    'strikeout_ratio': 'SUM(strike_outs) / SUM(CAST(batters_faced AS REAL)) AS strikeout_ratio',
    'walk_ratio': 'SUM(base_on_balls) / SUM(CAST(batters_faced AS REAL)) AS walk_ratio',
    'fly_outs': 'SUM(fly_outs) AS fly_outs',
    'ground_outs': 'SUM(ground_outs) AS ground_outs',
    'air_outs': 'SUM(air_outs) AS air_outs',
    'runs': 'SUM(runs) AS runs',
    'doubles': 'SUM(doubles) AS doubles',
    'triples': 'SUM(triples) AS triples',
    'home_runs': 'SUM(home_runs) AS home_runs',
    'at_bats': 'SUM(at_bats) AS at_bats',
    'balls': 'SUM(balls) AS balls',
    'strikes': 'SUM(strikes) AS strikes',
    'cumulative_pitches': 'GROUP_CONCAT(pitches_thrown) AS cumulative_pitches',
    'batters_faced': 'SUM(batters_faced) AS batters_faced',
    'pitches_thrown': 'SUM(pitches_thrown) AS pitches_thrown',
    'strike_outs': 'SUM(strike_outs) AS strike_outs',
    'walks': 'SUM(base_on_balls) AS walks',
    'k_bb': 'SUM(strike_outs) / CAST(SUM(base_on_balls) AS REAL) AS k_bb',
    'k_min_bb': '(CAST(SUM(strike_outs) AS REAL) / SUM(batters_faced)) - (CAST(SUM(base_on_balls) AS REAL) / '
                'SUM(batters_faced)) * 100.0 AS k_min_bb',
    'base_on_balls': 'SUM(base_on_balls) AS base_on_balls',
    'hits': 'SUM(hits) AS hits',
    'stolen_bases': 'SUM(stolen_bases) AS stolen_bases',
    'plate_appearances': 'SUM(plate_appearances) AS plate_appearances',
    'total_bases': 'SUM(total_bases) AS total_bases',
    'rbi': 'SUM(rbi) AS rbi',
    'sac_flies': 'SUM(sac_flies) AS sac_flies',
    'hit_by_pitch': 'SUM(hit_by_pitch) AS hit_by_pitch',
    'games': 'SUM(games_played) AS games',
    'W': 'SUM(wins) AS W',
    'CG': 'SUM(complete_games) AS CG',
    'SHO': 'SUM(shutouts) AS SHO',
    'H': 'SUM(hits) AS H',
    'ER': 'SUM(earned_runs) AS ER',
    'HBP': 'SUM(hit_by_pitch) AS HBP',
    'BB': 'SUM(base_on_balls) AS BB',
    'K': 'SUM(strike_outs) AS K',
    'predicted_pitches': 'GROUP_CONCAT(pitches_thrown) AS cumulative_pitches'
}
