swagger: "2.0"
info:
  title: "Baseball API"
  version: "1.0"
paths:
  /pitcher:
    get:
      operationId: "main_api.get_pitcher"
      responses:
        200:
          description: "Get stats for a pitcher"
      parameters:
        - name: "name"
          in: "query"
          type: "string"
          required: true
          description: "Name of the pitcher"
        - name: "start_date"
          in: "query"
          type: "string"
          format: "date"
          required: true
          description: "Start date"
        - name: "end_date"
          in: "query"
          type: "string"
          format: "date"
          required: true
          description: "End date"
        - name: "league"
          in: "query"
          type: "string"
          required: true
          description: "League"
  /batter:
    get:
      operationId: "main_api.get_batter"
      responses:
        200:
          description: "Get stats for a batter"
      parameters:
        - name: "name"
          in: "query"
          type: "string"
          required: true
          description: "Name of the batter"
        - name: "start_date"
          in: "query"
          type: "string"
          format: "date"
          required: true
          description: "Start date"
        - name: "end_date"
          in: "query"
          type: "string"
          format: "date"
          required: true
          description: "End date"
        - name: "league"
          in: "query"
          type: "string"
          required: true

