db_keys = {
    'play_id': 'TEXT PRIMARY KEY',
    'game_pk': 'INTEGER',
    'league': 'TEXT',
    'date': 'TEXT',
    'inning': 'INTEGER',
    'at_bat_index': 'INTEGER',
    'event': 'TEXT',
    'event_type': 'TEXT',
    'description': 'TEXT',
    'rbi': 'INTEGER',
    'batter_name': 'TEXT',
    'batter_id': 'INTEGER',
    'bat_side': 'TEXT',
    'pitcher_name': 'TEXT',
    'pitcher_id': 'INTEGER',
    'pitch_hand': 'TEXT',
    'pitch_result': 'TEXT',
    'launch_speed': 'REAL',
    'launch_angle': 'REAL',
    'total_distance': 'REAL',
    'trajectory': 'TEXT',
    'hardness': 'TEXT',
    'location': 'TEXT',
    'coord_x': 'REAL',
    'coord_y': 'REAL',
    'pitch_result_code': 'TEXT',
    'ball_color': 'TEXT',
    'trail_color': 'TEXT',
    'is_in_play': 'INTEGER',
    'is_strike': 'INTEGER',
    'is_ball': 'INTEGER',
    'pitch_code': 'TEXT',
    'pitch_name': 'TEXT',
    'is_out': 'INTEGER',
    'balls': 'INTEGER',
    'strikes': 'INTEGER',
    'outs': 'INTEGER',
    'start_speed': 'REAL',
    'end_speed': 'REAL',
    'strike_zone_top': 'REAL',
    'strike_zone_bottom': 'REAL',
    'strike_zone_width': 'REAL',
    'strike_zone_depth': 'REAL',
    'a_y': 'REAL',
    'a_z': 'REAL',
    'pfx_x': 'REAL',
    'pfx_z': 'REAL',
    'p_x': 'REAL',
    'p_z': 'REAL',
    'v_x0': 'REAL',
    'v_y0': 'REAL',
    'v_z0': 'REAL',
    'x': 'REAL',
    'y': 'REAL',
    'x0': 'REAL',
    'y0': 'REAL',
    'z0': 'REAL',
    'a_x': 'REAL',
    'break_angle': 'REAL',
    'break_length': 'REAL',
    'break_y': 'REAL',
    'break_vertical': 'REAL',
    'break_vertical_induced': 'REAL',
    'break_horizontal': 'REAL',
    'spin_rate': 'INTEGER',
    'spin_direction': 'INTEGER',
    'zone': 'INTEGER',
    'type_confidence': 'REAL',
    'plate_time': 'REAL',
    'extension': 'REAL',
    'play_events_index': 'INTEGER',
    'pitch_number': 'INTEGER',
    'disengagement_num': 'INTEGER',
    'from_catcher': 'INTEGER',
    'runner_going': 'INTEGER',
    'action_play_id': 'TEXT',
    'start_time': 'TEXT',
    'end_time': 'TEXT',
    'is_pitch': 'INTEGER',
    'type': 'TEXT',
    'away_score': 'INTEGER',
    'home_score': 'INTEGER',
    'half_inning': 'TEXT',
    'is_top_inning': 'INTEGER',
    'is_complete': 'INTEGER',
    'is_scoring_play': 'INTEGER',
    'has_out': 'INTEGER',
    'captivating_index': 'INTEGER',
    'final_balls': 'INTEGER',
    'final_strikes': 'INTEGER',
    'final_outs': 'INTEGER',
    'runner_on_1st': 'INTEGER',
    'runner_on_2nd': 'INTEGER',
    'runner_on_3rd': 'INTEGER',
    'game_type': 'TEXT',
    'game_type_name': 'TEXT',
    'season': 'TEXT',
    'day_night': 'TEXT',
    'time': 'TEXT',
    'venue_name': 'TEXT',
    'venue_id': 'INTEGER',
    'city': 'TEXT',
    'time_zone': 'TEXT',
    'turf_type': 'TEXT',
    'weather_condition': 'TEXT',
    'temp': 'TEXT',
    'wind': 'TEXT',
    'team_batting': 'TEXT',
    'team_batting_id': 'INTEGER',
    'team_batting_abbr': 'TEXT',
    'team_fielding': 'TEXT',
    'team_fielding_id': 'INTEGER',
    'team_fielding_abbr': 'TEXT',
    'official_scorer': 'TEXT'

}

sport_ids = {
    'MLB': 1,
    'AAA': 11,
    'AA': 12,
    'A+': 13,
    'A': 14,
    'ROOKIE BALL': 16,
    'WINTER LEAGUE': 17,
    'IND': 23
}

reversed_sport_ids = {
    1: 'MLB',
    11: 'AAA',
    12: 'AA',
    13: 'A+',
    14: 'A',
    16: 'ROOKIE BALL',
    17: 'WINTER LEAGUE',
    23: 'IND'
}

all_leagues = ['MLB', 'AAA', 'AA', 'A+', 'A', 'ROOKIE BALL', 'WINTER LEAGUE']

at_bat_events = [
    'Double', 'Strikeout', 'Flyout', 'Single', 'Forceout', 'Pop Out', 'Groundout',
    'GIDP', 'Field Error', 'Lineout', 'Fielders Choice', 'Double Play', 'Home Run', 'Stolen Base 3B', 'Triple',
    'Fielders Choice Out', 'Batter Out', 'Field Out', 'Strikeout Double Play', 'Bunt Pop Out',
    'Bunt Lineout', 'Bunt Groundout', 'Field Out', 'Batter Out', 'Triple Play', 'Runner Double Play'
]

pitch_names = [
    'Sinker', 'Slider', 'Changeup', 'Curveball', 'Cutter', '4-Seam Fastball',
    'Splitter', 'Sweeper', 'Knuckle Curve', 'Knuckle Ball', 'Slurve', 'Slow Curve',
    'Fastball', 'Eephus', 'Forkball', 'Screwball', '2-Seam Fastball'
]

game_types = {
    'S': 'Spring Training',
    'R': 'Regular Season',
    'F': 'Wild Card Game',
    'D': 'Division Series',
    'L': 'League Championship Series',
    'W': 'World Series',
    'C': 'Championship',
    'N': 'Nineteenth Century Series',
    'P': 'Playoffs',
    'A': 'All-Star Game',
    'I': 'Intrasquad',
    'E': 'Exhibition'
}

pitcher_db_keys = {
    'game_pk': 'INTEGER',
    'date': 'TEXT',
    'name': 'TEXT',
    'league': 'TEXT',
    'player_id': 'INTEGER',
    'jersey_number': 'TEXT',
    'position': 'TEXT',
    'position_code': 'TEXT',
    'note': 'TEXT',
    'summary': 'TEXT',
    'games_played': 'INTEGER',
    'games_started': 'INTEGER',
    'fly_outs': 'INTEGER',
    'ground_outs': 'INTEGER',
    'air_outs': 'INTEGER',
    'runs': 'INTEGER',
    'doubles': 'INTEGER',
    'triples': 'INTEGER',
    'home_runs': 'INTEGER',
    'strike_outs': 'INTEGER',
    'base_on_balls': 'INTEGER',
    'intentional_walks': 'INTEGER',
    'hits': 'INTEGER',
    'hit_by_pitch': 'INTEGER',
    'at_bats': 'INTEGER',
    'caught_stealing': 'INTEGER',
    'stolen_bases': 'INTEGER',
    'stolen_base_percentage': 'TEXT',
    'number_of_pitches': 'INTEGER',
    'innings_pitched': 'TEXT',
    'wins': 'INTEGER',
    'losses': 'INTEGER',
    'saves': 'INTEGER',
    'save_opportunities': 'INTEGER',
    'holds': 'INTEGER',
    'blown_saves': 'INTEGER',
    'earned_runs': 'INTEGER',
    'batters_faced': 'INTEGER',
    'outs': 'INTEGER',
    'games_pitched': 'INTEGER',
    'complete_games': 'INTEGER',
    'shutouts': 'INTEGER',
    'pitches_thrown': 'INTEGER',
    'balls': 'INTEGER',
    'strikes': 'INTEGER',
    'strike_percentage': 'TEXT',
    'hit_batsmen': 'INTEGER',
    'balks': 'INTEGER',
    'wild_pitches': 'INTEGER',
    'pickoffs': 'INTEGER',
    'rbi': 'INTEGER',
    'games_finished': 'INTEGER',
    'runs_scored_per9': 'TEXT',
    'home_runs_per9': 'TEXT',
    'inherited_runners': 'INTEGER',
    'inherited_runners_scored': 'INTEGER',
    'catchers_interference': 'INTEGER',
    'sac_bunts': 'INTEGER',
    'sac_flies': 'INTEGER',
    'passed_ball': 'INTEGER',
    'pop_outs': 'INTEGER',
    'line_outs': 'INTEGER',
    'game_type': 'TEXT',
    'game_type_name': 'TEXT',
    'season': 'TEXT',
    'day_night': 'TEXT',
    'time': 'TEXT',
    'venue_name': 'TEXT',
    'venue_id': 'INTEGER',
    'city': 'TEXT',
    'time_zone': 'TEXT',
    'turf_type': 'TEXT',
    'weather_condition': 'TEXT',
    'temp': 'TEXT',
    'wind': 'TEXT',
    'team_name': 'TEXT',
    'team_id': 'INTEGER',
    'team_abbr': 'TEXT'
}

hitter_db_keys = {
    'game_pk': 'INTEGER',
    'date': 'TEXT',
    'name': 'TEXT',
    'league': 'TEXT',
    'player_id': 'INTEGER',
    'jersey_number': 'TEXT',
    'position': 'TEXT',
    'position_code': 'TEXT',
    'summary': 'TEXT',
    'games_played': 'INTEGER',
    'fly_outs': 'INTEGER',
    'ground_outs': 'INTEGER',
    'air_outs': 'INTEGER',
    'runs': 'INTEGER',
    'doubles': 'INTEGER',
    'triples': 'INTEGER',
    'home_runs': 'INTEGER',
    'strike_outs': 'INTEGER',
    'base_on_balls': 'INTEGER',
    'intentional_walks': 'INTEGER',
    'hits': 'INTEGER',
    'hit_by_pitch': 'INTEGER',
    'at_bats': 'INTEGER',
    'caught_stealing': 'INTEGER',
    'stolen_bases': 'INTEGER',
    'stolen_base_percentage': 'TEXT',
    'ground_into_double_play': 'INTEGER',
    'ground_into_triple_play': 'INTEGER',
    'plate_appearances': 'INTEGER',
    'total_bases': 'INTEGER',
    'rbi': 'INTEGER',
    'left_on_base': 'INTEGER',
    'sac_bunts': 'INTEGER',
    'sac_flies': 'INTEGER',
    'catchers_interference': 'INTEGER',
    'pickoffs': 'INTEGER',
    'at_bats_per_home_run': 'TEXT',
    'pop_outs': 'INTEGER',
    'line_outs': 'INTEGER',
    'game_type': 'TEXT',
    'game_type_name': 'TEXT',
    'season': 'TEXT',
    'day_night': 'TEXT',
    'time': 'TEXT',
    'venue_name': 'TEXT',
    'venue_id': 'INTEGER',
    'city': 'TEXT',
    'time_zone': 'TEXT',
    'turf_type': 'TEXT',
    'weather_condition': 'TEXT',
    'temp': 'TEXT',
    'wind': 'TEXT',
    'team_name': 'TEXT',
    'team_id': 'INTEGER',
    'team_abbr': 'TEXT'
}

fielder_db_keys = {
    'game_pk': 'INTEGER',
    'date': 'TEXT',
    'name': 'TEXT',
    'league': 'TEXT',
    'player_id': 'INTEGER',
    'jersey_number': 'TEXT',
    'position': 'TEXT',
    'position_code': 'TEXT',
    'caught_stealing': 'INTEGER',
    'stolen_bases': 'INTEGER',
    'stolen_base_percentage': 'TEXT',
    'assists': 'INTEGER',
    'put_outs': 'INTEGER',
    'errors': 'INTEGER',
    'chances': 'INTEGER',
    'fielding': 'TEXT',
    'passed_ball': 'INTEGER',
    'pickoffs': 'INTEGER',
    'game_type': 'TEXT',
    'game_type_name': 'TEXT',
    'season': 'TEXT',
    'day_night': 'TEXT',
    'time': 'TEXT',
    'venue_name': 'TEXT',
    'venue_id': 'INTEGER',
    'city': 'TEXT',
    'time_zone': 'TEXT',
    'turf_type': 'TEXT',
    'weather_condition': 'TEXT',
    'temp': 'TEXT',
    'wind': 'TEXT',
    'team_name': 'TEXT',
    'team_id': 'INTEGER',
    'team_abbr': 'TEXT'
}

